### ISSUE TITLE
Fully standalone Shen/SCBL binary for Linux (with Nix or Guix)

### ISSUE THREAD

**Issue by Ambrevar** [Shen-Language/shen-cl#50] opened 2020-05-19 09:29 UTC
Non-FHS compliant operating systems like Nix and Guix won't be able to run the SBCL binary as is since the linker and the zlib library are not in /usr...

After patching the binary with `patchelf`, I get the following error:

```
> ./shen-cl-v3.0.3-linux-prebuilt/shen
fatal error encountered in SBCL pid 26743(tid 140737350383424):
can't find core file at /usr//lib/sbcl//sbcl.core
```

If I recall correctly, the error message is misleading and caused by the patchelf trick.  

If you want to distribute a truly standalone binary, consider using `guix pack -RR`.  This is what I do for https://next.atlas.engineer.  It works on _all_ GNU/Linux distributions.

Ideally, we would not need a binary to build Shen and bootstrap it from source completely.

**Comment by tizoc** [comment] 2020-05-19 12:26
The binaries are built on Travis-CI. I investigated a bit, and Guix is not supported, but [Nix is](https://docs.travis-ci.com/user/languages/nix)

This is not something I will be tackling in the near future, but I will leave this issue as a reminder for the future, a fully standalone binary for Linux would be good to have.

**Comment by bsima** [comment] 2020-05-20 06:01
@Ambrevar can you share what you've got so far? I started work on this today (as well as porting shen-scheme to nix) and I'm stuck at the bootstrapping phase. How can I compile shen in a nix environment without a working shen? I would like to get shen into nixpkgs upstream.

**Comment by tizoc** [comment] 2020-05-20 08:20
@bsima both Shen/Scheme and Shen/CL include precompiled code (in their respective target languages) in their source releases and can be built without needing a pre-existing Shen compiler in the system.

See the discussion here https://github.com/Shen-Language/shen-cl/issues/49

If you really need to compile from Shen code without using the precompiled files, see https://github.com/Shen-Language/shen-cl/issues/49#issuecomment-630949735

**Comment by Ambrevar** [comment] 2020-05-20 09:22
See issue #49 about boostrapping.  You need to build an old shen-scheme
first (based on Chibi), then a modern shen-scheme, then shen-cl.

**Comment by tizoc** [comment] 2020-05-20 09:46
@Ambrevar you don't need to do all that. There is only one extra compilation step required when starting from `.shen` source files instead of the provided precompiled `.lsp` ones. It can be done with any Shen implementation that is compliant enough to run the Shen code in this repository.

## Option 1 (building from precompiled files)

1.  Download the source release
2. With a working SBCL installed, do `make build-sbcl`

## Option 2 (building from shen source files)

This requires 

1. Download the source release or clone this repository
2. Do `make fetch` to download the Shen kernel sources
3. Do `make precompile SHEN=the-shen-you-have`
4. With a working SBCL installed, do `make build-sbcl`

Step 3 will only work if the Shen implementation you are using accepts the default command-line flags. If it doesn't, then you have to instead launch the REPL of that Shen implementation and load `scripts/build.shen` and then call the `build` function:

```
Shen, copyright (C) 2010-2015 Mark Tarver
www.shenlanguage.org, Shen 22.2
running under Scheme, implementation: chez-scheme
port 0.22 ported by Bruno Deferrari


(0-) (load "scripts/build.shen")
"Copyright (c) 2012-2019 Bruno Deferrari.  All rights reserved.
BSD 3-Clause License: http://opensource.org/licenses/BSD-3-Clause"
shen.x.factorise-defun.factorise-defun
shen.x.factorise-defun.factorise-cond
shen.x.factorise-defun.add-returns
shen.x.factorise-defun.generate-label
shen.x.factorise-defun.free-variables
shen.x.factorise-defun.free-variables-h
shen.x.factorise-defun.attach-free-variables
shen.x.factorise-defun.inline-mono-labels
shen.x.factorise-defun.rebranch
shen.x.factorise-defun.rebranch-h
shen.x.factorise-defun.true-branch
shen.x.factorise-defun.false-branch
shen.x.factorise-defun.with-labelled-else
shen.x.factorise-defun.merge-same-else-ifs
shen.x.factorise-defun.concat/
shen.x.factorise-defun.exp-var
shen.x.factorise-defun.optimize-selectors
shen.x.factorise-defun.test->selectors
shen.x.factorise-defun.bind-repeating-selectors
shen.x.factorise-defun.bind-selector

run time: 0.03141499999999997 secs
loaded
shen-cl.initialise-compiler
shen-cl.kl
shen-cl.cl
shen-cl.unbound-symbol?
shen-cl.merge-nested-repeats
shen-cl.merge-nested-lets
shen-cl.compile-expression
shen-cl.optimise-boolean-check
shen-cl.emit-symbol
shen-cl.subst*
shen-cl.ch-T/NIL
shen-cl.emit-let
shen-cl.emit-lambda
shen-cl.emit-if
shen-cl.emit-cond
shen-cl.emit-cond-clauses
shen-cl.emit-trap-error
shen-cl.emit-trap-error-optimise
shen-cl.emit-equality-check
shen-cl.emit-application
shen-cl.is-partial-application?
shen-cl.take
shen-cl.drop
shen-cl.emit-partial-application
shen-cl.dynamic-application?
shen-cl.emit-dynamic-application
shen-cl.lisp-prefixed-h?
shen-cl.lisp-prefixed?
shen-cl.remove-lisp-prefix
shen-cl.upcase
shen-cl.upcase-h
shen-cl.upcase-char
shen-cl.upcase-charcode
shen-cl.qualify-op
shen-cl.not-fail
shen-cl.binary-op-mapping
shen-cl.unary-op-mapping
shen-cl.optimise-static-application
shen-cl.emit-static-application
shen-cl.emit-application*
shen-cl.nest-call
shen-cl.nest-lambda
shen-cl.merge-args
shen-cl.factorise-defun
shen-cl.add-block
shen-cl.kl->lisp

run time: 0.08119700000000002 secs
loaded
shen-cl.done
true
10000
["toplevel" "core" "sys" "dict" "sequent" "yacc" "reader" "prolog" "track" "load" "writer" "macros" "declarations" "types" "t-star" "init" "extension-features" "extension-launcher" "extension-factorise-defun"]
["compiler"]
for-each
sexp->string
cased-symbol?
lowercase?
symbol->string
concat-strings
compile-defun
write-license-comment
add-comments
write-license-string
file-license
extract-license
bytes->string
compile-kl-file
make-kl-code
compile-shen-file
build
write-string-to-file
package-prelude

run time: 0.137105 secs
loaded

(1-) (build)
Compiling "kernel/klambda/compiler.kl"...
Compiling "kernel/klambda/toplevel.kl"...
Compiling "kernel/klambda/core.kl"...
Compiling "kernel/klambda/sys.kl"...
Compiling "kernel/klambda/dict.kl"...
Compiling "kernel/klambda/sequent.kl"...
Compiling "kernel/klambda/yacc.kl"...
Compiling "kernel/klambda/reader.kl"...
Compiling "kernel/klambda/prolog.kl"...
Compiling "kernel/klambda/track.kl"...
Compiling "kernel/klambda/load.kl"...
Compiling "kernel/klambda/writer.kl"...
Compiling "kernel/klambda/macros.kl"...
Compiling "kernel/klambda/declarations.kl"...
Compiling "kernel/klambda/types.kl"...
Compiling "kernel/klambda/t-star.kl"...
Compiling "kernel/klambda/init.kl"...
Compiling "kernel/klambda/extension-features.kl"...
Compiling "kernel/klambda/extension-launcher.kl"...
Compiling "kernel/klambda/extension-factorise-defun.kl"...
done

(2-) 
```

**Comment by tizoc** [comment] 2020-05-20 09:51
Btw, if you guys produce Guix or Nix packages, please let me know so that I can mention that in the README as an installation option.

**Comment by Ambrevar** [comment] 2020-05-20 10:15
@Bruno: I meant a bootstrapped build (that does not need an existing Shen).  Neither the option 1
nor the option 2 you mentioned is bootstrapped.

**Comment by tizoc** [comment] 2020-05-20 10:25
Sorry, I think I'm missing something here. Can you tell me how is option 2 different from the examples from the website you shared? https://www.bootstrappable.org/best-practises.html#compiler

**Comment by myguidingstar** [comment] 2020-05-20 11:21
I thought Option 1 does not work out of the box, got this error:
```
Directory "./compiled/" not found.
Run 'make precompile' to precompile the kernel and compiler.
```
Then I looked at the release files again, it turns out that the file for option 1 is `shen-cl-v3.0.3-sources.tar.gz`. I used a git clone, therefore no "compiled" directory.
![image](https://user-images.githubusercontent.com/28971161/82440523-aaebbe80-9ac6-11ea-8e20-59c9af477503.png)

**Comment by Ambrevar** [comment] 2020-05-20 11:39
In your option #2 you are missing the following point: that the other
the-shen-you-have must be boostrappable.  This is why I mentioned the
Chibi Shen in my comment above.  In the end "bootstrappable option #2" is
equivalent to my comment.

**Comment by tizoc** [comment] 2020-05-20 13:24
If you don't consider ShenScript and ShenWasp bootstrappable, then you shouldn't consider Chibi Shen bootstrappable either. All three implementations do the same, they load code written in their respective languages, and that code implements the KLambda compiler and runtime that is then used to run Shen.

Now, depending on how high the standards you set are, it is not possible for any Shen implementation to be bootstrappable if you take into account that what they all do is compile/execute KLambda code that was produced by a compiler that took Shen code as input and produced KLambda as output. This went through many iterations for many many years, even from before Shen existed (it was Qi back then), and it is not possible to reproduce all that chain now.

But that assumes that KLambda is the same as bytecode or a binary.

If you pretty-print KLambda code, you will see that it is just Shen macroexpanded, and without pattern matching, and it is perfectly readable. But the same can be said about the Common Lisp and Scheme code from Shen/CL and Shen/Scheme, and the mapping from KLambda to any of them is a smaller jump than Shen->KLambda is.

**Comment by myguidingstar** [comment] 2020-05-20 14:13
I've just pushed the build script for shen/sbcl for nix here https://github.com/myguidingstar/shen-nix

**Comment by tizoc** [comment] 2020-05-21 12:54
@myguidingstar so, how does this work? is that something you will submit to Nix's repository and it will then be available? I'm very vaguely familiar with Nix.

**Comment by myguidingstar** [comment] 2020-05-21 13:44
I created two nix "package": one for shen-os and one for shen-sbcl. Shen-sbcl dedends on shen-os and sbcl.
- shen-os does nothing but extract the archive
- shen-sbcl's build script creates a symlink `kernel` to shen-os, then run `make sbcl` to compile. The `shen` binary is copied to output
However, I'm not familiar with shen (I learned Qi years ago), and don't know what to do with other shen and lisp files in shen-sbcl's output.

I'm not going to submit them soon as I don't really use them, just curious how shen looks like after years. Someone can definitely continue the work and have better idea about where to put the said shen and lisp files.

**Comment by myguidingstar** [comment] 2020-05-21 13:49
Update: just set license to public domain

**Comment by tizoc** [comment] 2020-05-21 15:38
@myguidingstar the only thing that matters is the binary, the `.shen` files are either source code or tests.

**Comment by Ambrevar** [comment] 2020-05-22 08:59
@Bruno:

> But that assumes that KLambda is the same as bytecode or a binary.
> If you pretty-print KLambda code, you will see that it is just Shen macroexpanded, and without pattern matching, and it is perfectly readable. But the same can be said about the Common Lisp and Scheme code from Shen/CL and Shen/Scheme, and the mapping from KLambda to any of them is a smaller jump than Shen->KLambda is.

Looking at a simple function in compiled/compiler.lsp:

```
(DEFUN |shen-cl.unbound-symbol?| (V503 V504 )
  (BLOCK ()
    (IF (OR (|shen-cl.true?| (|symbol?| V503 )
            (EQ V503 '|,| ))
        (RETURN (|not| (|element?| V503 V504 )))
        (RETURN '|false| ))))
```

While this is Lisp, there is no comment and symbols have no meaningful
names.  In other words, this does not seem to be very different from
disassembled code.

Or is there a more readable version?

> This went through many iterations for many many years, even from
> before Shen existed (it was Qi back then), and it is not possible to
> reproduce all that chain now.

Some people are working hard at making C bootstrappable again (See the
GNU Mes project).  Work was done for Haskell, Rust (mrust) and a few
other languages.

The chain might be long, but it no information was lost in the past,
then it can be done for Shen too.

**Comment by tizoc** [comment] 2020-05-22 13:18
Hi @Ambrevar.

What you say is true, but consider that in Shen it is very common for function parameters to not have a variable associated with them (because of pattern matching), so those have to be made up. Anything that is then bound inside the function (even directly through `let` or because of pattern matching) retains it's name. Same goes for functions. The only names that exist in the original source code that are lost in translation are variables that are function parameters. But if you read Shen's kernel source code you will also see that variable names like `X`, `Y`, `N`, etc are very usual names for function parameters, which are not terribly more meaningful than `V123`. There aren't many comments in it either.

Also, unlike in decompiled code, here structure is maintained, and the mapping from Shen->Klambda->Lisp/Scheme is *by far* much simpler than what you get from GCC/GHC/etc to machine code being that the languages are much closer and the transformations that happen along the way are far simpler. In addition, Shen's source code is many orders of magnitude shorter (roughly 5k lines between the kernel, extensions and compiler code for either Lisp or Scheme ports).

> Or is there a more readable version?

There doesn't exist a more readable version in that sense, but Scheme's output is probably going to look nicer because it doesn't have to do weird stuff with the reader like the Common Lisp port (uppercase output with `||` to keep Shen-side symbols lowercase). And if you disable the pattern matching factorization optimization that goes another step (applies to the Common Lisp port too, because then the output doesn't contain `BLOCK`, `TAGBODY`, `RETURN`, or `GO`).

So, while the code is not something that would be pretty to maintain if that is what you had to work with, I think it is far better than disassembled code.

> The chain might be long, but it no information was lost in the past,
then it can be done for Shen too.

I don't think that will be possible, what you can do is establish trust (which I think is what it all boils down to) in one of the versions that is available now, and consider that one as the root. Once you trust that "root", you can easily compare the output generated by running different versions and see that they match.

Btw "@bruno" is someone else's handle, that person must be confused!

**Comment by tizoc** [comment] 2020-05-22 16:18
> There doesn't exist a more readable version in that sense, but Scheme's output is probably going to look nice ......snip

Btw, if you think this is useful let me know and I will show you how. It is the best solution I can think of at the moment.

**Comment by tizoc** [comment] 2020-05-22 17:34
Thinking about it some more, it is only the KLambda code that you have to trust, because that is what every port loads to go from KLambda implementation to a full Shen one. And KLambda is the broken link that you cannot track back to the original source right now.

**Comment by Ambrevar** [comment] 2020-05-25 12:10
Could you document this KLambda implementation (URL with exact commit
for instance)?

Then all we need to do is write a document that fully describe this
KLambda code.  I guess that could be considered open enough.

Thoughts?

**Comment by tizoc** [comment] 2020-05-25 13:27
> Could you document this KLambda implementation (URL with exact commit
for instance)?

Sorry, not sure I follow. Every port is a KLambda implementation, there is not a particular commit I can point to.

If you mean the KLambda files, those are available in the [kernel source releases](https://github.com/Shen-Language/shen-sources/releases) and are not part of the repository because they are automatically generated. These KLambda files are what ports load to complete their implementation and become full Shen implementations. Also, in general, each released version is used to build the next release (22.3 was built by 22.2, which was itself built by 22.1, etc).

To make KLambda code prettier you can use Common Lisp's pretty printer. There is a 1-to-1 mapping between Shen's source code and those KLambda files (for each `.shen` file there is one `.kl` file with the same name, and for each function in one of those `.shen` files you will find a matching function in the `.kl` file with the same name). Then there is one additional file `init.kl` which includes any top-level code that was found in other files and is not a function definition (basically code to initialize constants and data used by the compiler).

Note that ports may choose to override functions with their own. If you see some function in a `.kl` file, that doesn't guarantee that a port will use it. The usual reason to not do it is that the port can provide a more performant version by taking advantage of functionality provided by the underlying platform.

The KLambda language is described [here](https://github.com/Shen-Language/wiki/wiki/KLambda) and in [Shen's spec document](http://shenlanguage.org/shendoc.htm). It is a small and limited language, far simpler than Scheme. That is why it is so easy to implement a Shen port compared to other languages.

The compilation from Shen to KLambda is performed by the Shen compiler written in Shen itself, and that code lives in the [Shen kernel sources repository](https://github.com/Shen-Language/shen-sources).

How Shen is compiled into KLambda is documented in the [Shen book](http://shenlanguage.org/learn.htm), which is only available in printed form.

Most of the Shen to KLambda conversion is quite direct and simple. The parts that are not that simple are the compilation of pattern-matching, YACC and Prolog, but I would say that those parts are still simpler than what you will find in most compilers.

**Comment by tizoc** [comment] 2020-05-25 13:33
@Ambrevar another thing, KLambda and Shen don't know anything about the underlying implementation, everything is done on top of 50-ish primitives that each port has to provide. This is an important detail because I think it makes it far easier to verify that the compiler is not performing any hostile operations during code generation.

**Comment by Ambrevar** [comment] 2020-05-25 13:44
Previously you said

> Thinking about it some more, it is only the KLambda code that you have to trust, because that is what every port loads to go from KLambda implementation to a full Shen one. And KLambda is
> the broken link that you cannot track back to the original source right now.

What I was suggesting was to pinpoint this "broken link", which is
written in KLambda, right?  Then document it.

**Comment by tizoc** [comment] 2020-05-25 13:56
I is the part that is machine-generated, which as far as I understand, based on your criteria, is a "black box" like bytecode or native code are, and because of that, it breaks the chain of trust. 

> Then document it.

No. I'm trying to guide you in the right direction so that you can fulfill the objective you have. It is not something I myself consider a problem that applies to Shen. Neither do I have the time or will to do that because to me it is not worth it. What I can do, is assist you if you decide to go down that path.

**Comment by Ambrevar** [comment] 2020-05-25 15:14
I'm not in a good position to bootstrap Shen since I'm not a Shen
developer.

> It is not something I myself consider a problem that applies to Shen.

But why not?  Right now, we have no way to trust Shen since, you said it
yourself, there is a broken link.

The amount of work to prove that Shen does not have malicious code in it
is significant as you highlighted in your post before the last one.

**Comment by tizoc** [comment] 2020-05-26 11:57
> But why not?  Right now, we have no way to trust Shen since, you said it
yourself, there is a broken link.

Yes, but I say that based on what I understand are your assumptions and criteria, not based on mine.

Correct me if I'm wrong, but to you, the code linked below is a black box on the same level as bytecode, native code, and output generated by an de-compiler:

https://gist.github.com/tizoc/93eb86f6cb7ba4724e4ca5bb1e5a8914

Since the way such code came to exists, was through many iterations that go back to a binary for which we don't have the source code, and because of that, we cannot produce our own verified copy (we don't even have such binary at this point).

is that correct?

That is what makes the KLambda code the broken link (again, based on my understanding of what your criteria is, it isn't a broken link based on mine, because I don't see that code in the same way you do).

> The amount of work to prove that Shen does not have malicious code in it
is significant as you highlighted in your post before the last one.

You misunderstood me, I claim the opposite. That klambda code is not equivalent to bytecode, native code or de-compiled code, neither on size, distance from the original code from which it was produced, or opaqueness.

**Comment by Ambrevar** [comment] 2020-05-26 12:45
This is a delicate matter indeed.

Maybe it would be worth bringing this up to the bootstrapping community
see what others think.

**Comment by tizoc** [comment] 2020-05-26 12:59
Sounds good to me. I'm no expert, just a guy very familiar with Shen and its internals.

**Comment by bsima** [comment] 2020-09-09 20:00
The [NixOS MR](https://github.com/NixOS/nixpkgs/pull/88915) was recently merged, so this can probably be closed. The bootstrapping issue is a different topic IMO.

**Comment by tizoc** [comment] 2020-09-13 14:06
@bsima thank you!

**Closed as completed** 2020-09-13 14:06 UTC
Labels: enhancement, linux

**Comment by ghost** [comment] 2021-10-24 01:27
Some free information for the concerned;
The current nix shen-sbcl does build, but the resulting binary is broken, complains of missing sbcl-core. If memory serves right, the guix build had the same problem.

Ecl is used currently for uniks bootstrap to get around that problem.
link: https://github.com/maisiliym/uniks/blob/42dc9a8bc60ca6d96310cc4b8c8c320ae9d647e3/nix/pkdjz/shen/ecl.nix
